### ISSUE TITLE
Error with "ngrok"

### ISSUE THREAD

**Issue by greatgaming23** [FDX100/Phisher-man#1]
Everytime I pick a choice of which website, I get a ngrok error that says "./ngrok: 1: ./ngrok: Syntax error: "(" unexpected" 

Picture of my Kali Linux and the errror : https://imgur.com/a/Uwvlr8U

**Comment by FDX100** [comment]
your Kali Linux is 32 bit and you should install 64 bit but you can do this 
go to Phisher-man folder delete ngrok file 
then download this ngrok (https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip)
after that open zip file and put ngrok file in it in Phisher-man folder
