### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by excep** [FDX100/Phisher-man#3]
Typed this : python phisherman.py

And this pops up :

  File "phisherman.py", line 71
    print "Now apache is clean 3:)"
                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Now apache is clean 3:)")?

**Comment by SurajBhari** [comment]
it is written in python2.
use python2 phisherman.py

**Comment by FDX100** [comment]
fixed in version 2
